### ISSUE TITLE
4th Edition schema does not complain about certain test vectors

### ISSUE THREAD

**Issue by eceozturk** [Dash-Industry-Forum/MPEG#11]
Some of the test vectors have schema errors which are correctly reported when tested against previous schema editions. However these errors are not reported when tested against the 4th edition schema.

**NOTE: This issue is still being investigated.**

__Tested DASH schema location__ (4th edition, with profile string regex modified to include "/" and "#"):
https://raw.githubusercontent.com/eceozturk/DASHSchema/dev/DASH-MPD.xsd

__Testing URL:__
http://54.72.87.160/conformance/current/Conformance-Frontend/Conformancetest.php?schema=https://raw.githubusercontent.com/eceozturk/DASHSchema/dev/DASH-MPD.xsd

__Problematic test vectors:__
* https://livesim.dashif.org/livesim/periods_60/mpdcallback_30/testpic_2s/Manifest.mpd
    * "Attribute 'messageData' is not allowed to appear in element 'EventStream'." error should be reported for this test vector; however, it passes the conformance test.
* https://dash.akamaized.net/dash264/TestCasesIOP33/resolveToZero/1/manifest.mpd
    * "Attribute 'schemeIdUri' must appear on element 'AssetIdentifier'." error should be reported for this test vector; however, it passes the conformance test.
* https://dash.akamaized.net/dash264/TestCasesHD/MultiPeriod_OnDemand/ThreePeriods/ThreePeriod_OnDemand_presentationDur_AudioTrim.mpd
    * "'25.7726666667' is not a valid value for 'integer'. The value '25.7726666667' of attribute 'presentationDuration' on element 'SegmentBase' is not valid with respect to its type, 'unsignedLong'." error should be reported for this test vector; however, it passes the conformance test.

**Comment by haudiobe** [comment]
Put this forward to MPEG Schema Issues @mikedo

**Comment by mikedo** [comment]
General issue with DASH Schema identified in https://github.com/MPEGGroup/DASHSchema/issues/47

**Comment by paulhiggs** [comment]
My last three comments on [MPEGGroup/DASHSchema#47](https://github.com/MPEGGroup/DASHSchema/issues/47) identify the problem. You can make a local schema change to have something valid to test against

**Comment by eceozturk** [comment]
I have done regression testing with the latest schema change, and confirm that this issue is resolved.
